### ISSUE TITLE
iPad: fails on first tap

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-globalAudio#3]
While testing https://olivermartinfoster.github.io/globalAudio/ on
Safari 
iPadOS 14.51OS

Actual Behaviour:  
1, When I tap the Play icon, it changes to Pause icon, then immediately back to the Play button. No audio is heard throughout.
2. Then I tap the Play icon a second time, it changes to Pause icon and audio is heard.
This behaviour occurs for me on all instances of globalAudio regardless of location or src file.

Expected Behaviour:
Tap the Play icon; it changes to Pause; audio is heard.

**Comment by oliverfoster** [comment]
Could you give it another try? https://olivermartinfoster.github.io/globalAudio/

**Comment by chucklorenz** [comment]
Yes. Tried it. No difference. Same errant behaviour. I attempted to "clear the cache" before retrying. But Safari doesn't give me confidence that I did it right. I don't want to lose all my browsing history, so I went into Settings > Safari > Advanced > Website Data, then deleted olivermartinfoster.github.io/globalAudio/ . No change. Happy to accept suggestions.

**Comment by oliverfoster** [comment]
Lets rule that out altogether: https://olivermartinfoster.github.io/globalAudio1/
